### GENERAL SETTINGS ###

# Site settings
title: MaptimeAlpes
description: "We make maps in the Alps. On fait de la cartographie dans les Alpes!"
baseurl: ""
url: "http://www.maptime-alpes.com"

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" 
  primary_rgb: "0,179,254" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452"
  secondary_rgb: "56,68,82"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# locale settings
default_locale:     "en"
authorized_locales: 
  - tag: "en"
    flag: "United-States-of-America.png"
  - tag: "fr"
    flag: "France.png"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: "https://twitter.com/MaptimeAlpes"
  - title: github
    url: "https://github.com/MaptimeAlpes"
  - title: meetup
    url: "http://www.meetup.com/MaptimeAlpes/"

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: adamben.roberts@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We make maps in the Alps. On fait de la cartographie dans les Alpes!"